name: Android Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.26-4/x64
